tailgate_uwp_add_library(
    Tailgate.Uwp.Background.Manager
    STATIC
    ChannelPolicy.cpp
    ChannelPolicy.h
    ControlPlaneManager.h
    ControlRegistrationNotification.cpp
    ControlRegistrationNotification.h
    DataPlaneManager.h
    impl/ControlPlaneManagerImpl.cpp
    impl/ControlPlaneManagerImpl.h
    impl/DataPlaneManagerImpl.cpp
    impl/DataPlaneManagerImpl.h
    impl/ProfileRecoveryManagerImpl.cpp
    impl/ProfileRecoveryManagerImpl.h
    impl/SessionManagerImpl.cpp
    impl/SessionManagerImpl.h
    ProfileRecoveryManager.cpp
    ProfileRecoveryManager.h
    ProfileRecoveryState.h
    SessionManager.h
)
target_include_directories(
    Tailgate.Uwp.Background.Manager
    PUBLIC
        "${CMAKE_CURRENT_SOURCE_DIR}/.."
)
target_link_libraries(
    Tailgate.Uwp.Background.Manager
    PUBLIC
        tailgate_core
    PRIVATE
        Tailgate.Uwp.Common
        nlohmann_json::nlohmann_json
)
