tailgate_add_test_executable(
    tailgate_linux_tests
    Given_FdStream.cpp
    Given_LinuxBindings.cpp
    Given_LinuxDataplaneEvents.cpp
    Given_LinuxPeerApiServer.cpp
    Given_LinuxPingIpc.cpp
    Given_LinuxQrCode.cpp
    Given_LinuxState.cpp
    LinuxTestEnvironment.h
)
target_include_directories(
    tailgate_linux_tests
    PRIVATE ${PROJECT_SOURCE_DIR}/src/platform/linux
)
target_link_libraries(
    tailgate_linux_tests
    PRIVATE
        tailgate_tests
        tailgate_linux
)
