add_subdirectory(base)
add_subdirectory(control)
add_subdirectory(crypto)
add_subdirectory(derp)
add_subdirectory(di)
add_subdirectory(disco)
add_subdirectory(hosted)
add_subdirectory(net)
add_subdirectory(qr)
add_subdirectory(serve)
add_subdirectory(types)
add_subdirectory(wgengine)

add_library(tailgate_core INTERFACE)
target_link_libraries(
    tailgate_core
    INTERFACE
        tailgate_core_base
        tailgate_core_control_base
        tailgate_core_control_client
        tailgate_core_crypto
        tailgate_core_derp
        tailgate_core_di
        tailgate_core_disco
        tailgate_core_hosted
        tailgate_core_net_dns
        tailgate_core_net_packet
        tailgate_core_net_stun
        tailgate_core_net_tls
        tailgate_core_qr
        tailgate_core_serve
        tailgate_core_serve_acme
        tailgate_core_types_netmap
        tailgate_core_wgengine_wireguard
)
