add_subdirectory(core)
add_subdirectory(capi)
add_subdirectory(cli)
if(TAILGATE_BUILD_LINUX)
    if(NOT LINUX)
        message(FATAL_ERROR "The Tailgate Linux frontend requires Linux")
    endif()
    add_subdirectory(platform/linux)
endif()
if(TAILGATE_BUILD_UWP)
    if(NOT WIN32)
        message(FATAL_ERROR "The Tailgate UWP frontend requires Windows")
    endif()
    add_subdirectory(platform/uwp)
endif()
