add_subdirectory(core)
add_subdirectory(capi)
if(TAILGATE_BUILD_FRONTEND)
    if(NOT UNIX OR WIN32)
        message(FATAL_ERROR "The available Tailgate frontend requires Linux")
    endif()
    add_subdirectory(linux)
endif()
if(TAILGATE_BUILD_FRONTEND OR TAILGATE_BUILD_TESTS)
    add_subdirectory(cli)
endif()
