function(_tailgate_target_add_warning_flags target)
    if(CMAKE_CXX_COMPILER_ID MATCHES "Clang|GNU")
        target_compile_options(${target} PRIVATE -Wall -Wextra -Wpedantic -Werror)
    endif()
endfunction()

function(_tailgate_configure_target target)
    target_include_directories(${target} PUBLIC ${PROJECT_SOURCE_DIR}/include)
    _tailgate_target_add_warning_flags(${target})
    tailgate_target_add_sanitizers(${target})
    tailgate_target_add_pdb(${target})
endfunction()

function(tailgate_add_library target type)
    add_library(${target} ${type} ${ARGN})
    _tailgate_configure_target(${target})
endfunction()

function(tailgate_add_third_party_library target type)
    add_library(${target} ${type} ${ARGN})
    target_include_directories(${target} PUBLIC ${PROJECT_SOURCE_DIR}/include)
    tailgate_target_add_sanitizers(${target})
    tailgate_target_add_pdb(${target})
endfunction()

function(tailgate_add_executable target)
    add_executable(${target} ${ARGN})
    set_target_properties(${target} PROPERTIES RUNTIME_OUTPUT_DIRECTORY ${PROJECT_BINARY_DIR})
    _tailgate_configure_target(${target})
    if(CMAKE_CXX_COMPILER_ID MATCHES "Clang|GNU" AND
       NOT TAILGATE_SANITIZER_PREVENT_STATIC_LINKING)
        target_link_options(${target} PRIVATE -static)
    endif()
endfunction()
