if(TAILGATE_BUILD_TESTS)
    include(CTest)
    include(GoogleTest)

    function(tailgate_add_test_executable target)
        tailgate_add_executable(${target} ${ARGN})
        target_link_libraries(${target} PRIVATE GTest::gtest_main)
        gtest_discover_tests(${target} DISCOVERY_MODE PRE_TEST)
    endfunction()
endif()
