tailgate_uwp_add_test_library(
    tailgate_tests_uwp_bg
    Given_DataPlaneManager.cpp
    Given_ExitNodeService.cpp
    Given_HostedDnsService.cpp
    Given_NetworkService.cpp
    Given_PingService.cpp
    Given_SessionManager.cpp
)
target_include_directories(
    tailgate_tests_uwp_bg
    PRIVATE
        "${PROJECT_SOURCE_DIR}/src/platform/uwp"
        "${PROJECT_SOURCE_DIR}/tests/uwp"
)
target_link_libraries(
    tailgate_tests_uwp_bg
    PRIVATE
        Boost.DI
        Tailgate.Uwp.Background.Manager
        Tailgate.Uwp.Background.Service
        Tailgate.Uwp.Common
)
